apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: sriuday19/vprofileapp
        ports:
        - containerPort: 8080
          name: vpro-app-port
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done']
        - name: init-memcache
          image: busybox
          command: ['sh', '-c', 'until nslookup mc01; do echo waiting for mydb; sleep 2; done']
