apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb  
spec:
  selector:
    matchLabels:
      app: vprodb 
  template:
    metadata:
      labels:
        app: vprodb 
    spec:
      containers:
      - name: vprodb
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
        image: sriuday19/vprofiledb
        ports:
        - containerPort: 3306
          name: vpro-db-port
        env:
          - name: MYSQl_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-serets
                key: db-pass
      nodeSelector:
        zone: us-east-1c
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-099f8aace61be5023 
            fsType: ext4

      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm","-rf","/var/lib/mysql/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data 
